### ISSUE TITLE
OpenTTD 14 removed share owners

### ISSUE THREAD

**Issue by rubidium42** [miltschek/OpenTTDAdmin#1]
With OpenTTD/OpenTTD#10709 company shares have been removed, including from he admin packet with an increment of the protocol version number.

Given the code reads from a much bigger array, it won't overflow and does throw an exception. However, it happily returns that the company with id 0 owns 100% of the company. That might trip up any users of this library. 
https://github.com/miltschek/OpenTTDAdmin/blob/411a2a571ae52159be31d4eab0544ae290d3cab9/ottdclient/src/main/java/de/miltschek/openttdadmin/packets/ServerCompanyInfo.java#L53-L55

I would suggest reading the protocol version and based on the version make a choice on how to decode the packet. In case of version 3 and later that would exclude reading the share owners, but explicitly setting them to 255.

**Comment by miltschek** [comment]
Thank you for the report. I will take a look at the last protocol changes and adjust the library accordingly.

**Comment by miltschek** [comment]
Solved in https://github.com/miltschek/OpenTTDAdmin/releases/tag/1.4.0
